### ISSUE TITLE
Module path should be "github.com/pouriyajamshidi/tcping", not "tcping"

### ISSUE THREAD

**Issue by nohupped** [pouriyajamshidi/tcping#1]
Hi,
Thank you for this program. 

Do you have plans to make this go gettable by changing the module path from `tcping` to `github.com/pouriyajamshidi/tcping` in the go.mod file?

```
 🕙 05:58:54 ❯ go get github.com/pouriyajamshidi/tcping
go: downloading github.com/pouriyajamshidi/tcping v1.2.0
go get: github.com/pouriyajamshidi/tcping@v1.2.0: parsing go.mod:
	module declares its path as: tcping
	        but was required as: github.com/pouriyajamshidi/tcping
```

**Comment by pouriyajamshidi** [comment]
Hi,

You  are very welcome!

Yes, I will apply the modification and make it go gettable soon! 

Stay tuned.

**Comment by pouriyajamshidi** [comment]
Should be fine now. Could you please confirm?

**Comment by nohupped** [comment]
Thank you. I confirm it is working with a `go get` now.

**Comment by pouriyajamshidi** [comment]
You are welcome and thanks for bringing this to my attention.
