### ISSUE TITLE
README Translation - Chinese

### ISSUE THREAD

**Issue by pouriyajamshidi** [pouriyajamshidi/tcping#105]
### TL;DR

We need community contributors to add Chinese (Mandarin or Cantonese or both) documentation for this project.

---

`TCPING` has come a long way and we have a lot of users from all around the world.

This issue along some others, will ask the community for contributions to add README files in Chinese (Mandarin or Cantonese or both) to broaden the reach of the tool.

**Comment by edwinjhlee** [comment]
I can help ~

I am the author of x-cmd. I am Chinese ~

Recently I am finding a cross-platform ping tool. Then I found this project.

---

We already have gping and nping.

gping is fine. But lack of text-based output, which is complained by our users: https://github.com/orf/gping/issues/483
nping is allowed to be redistributed in windows: https://cn.x-cmd.com/pkg/nping
