### ISSUE TITLE
output interface

### ISSUE THREAD

**Issue by cyayon** [pouriyajamshidi/tcping#123]
Hi, 

Could you please add the possibility to define output interface ?
I am using this to monitor multiple wan links.

Thanks.

**Comment by pouriyajamshidi** [comment]
Hi,

Sure. This is a good feature request.

**Comment by wizsk** [comment]
can you please describe the feature?

**Comment by pouriyajamshidi** [comment]
Hi @wizsk,

A new flag, `-i` has to be defined which takes the interface name from the user, say `eth0` and then uses that interface to Dial the TCP connection.

**Comment by AKARSHITJOSHI** [comment]
Hi @pouriyajamshidi I would like to give this a try.

**Comment by cyayon** [comment]
Hi,
it multiple ip addresses are defined on the interface, how does it work ?
Do you use the first/last source ip address ? 
thanks.

**Comment by pouriyajamshidi** [comment]
> Hi @pouriyajamshidi I would like to give this a try. Let me know where to get started.

Hi @AKARSHITJOSHI,

You can start by forking the repo, working on the feature as described above and open a pull request for it. Then we will review it and if you need help or there are some parts that need to be aligned, we will communicate on that PR with you.

**Comment by pouriyajamshidi** [comment]
> Hi, if multiple ip addresses are defined on the interface, how does it work ? Do you use the first/last source ip address ? thanks.

Hi,

That's a good question. No idea to be frank as we speak. Maybe that can be baked into the code but it might make it a bit too complicated.

What is the ideal behavior in your opinion?

**Comment by cyayon** [comment]
Perhaps doing like ping or curl.
In case of interface, use the first address. 
Add the ability to define source address with -s or something like that...

**Comment by wizsk** [comment]
Hey @pouriyajamshidi I can help 
But what does Interface do? Can you please explain a little?

**Comment by pouriyajamshidi** [comment]
Hey @wizsk,

It is a mechanism for the user to specify the source IP address or which network interface to use. Similar to the `-I` flag of the **ping** utility:

```console
$ ping --help

-I <interface>     either interface name or address
```

It is worthwhile to mention that if an interface has multiple IP addresses, the first one should be used.

**Comment by wizsk** [comment]
@pouriyajamshidi 
Got it.

**Comment by wizsk** [comment]
@pouriyajamshidi started working on this. I will make a pr when its ready

**Comment by pouriyajamshidi** [comment]
> @pouriyajamshidi started working on this. I will make a pr when its ready

good luck! thanks :)
