### ISSUE TITLE
v2.0.0 is not listed on Go module proxy due to missing /v2 suffix in the "module" path

### ISSUE THREAD

**Issue by ehaupt** [pouriyajamshidi/tcping#126]
**Describe the bug**
The most recent version [v2.0.0](https://github.com/pouriyajamshidi/tcping/releases/tag/v2.0.0) is not listed on the [Go module proxy](https://pkg.go.dev/github.com/pouriyajamshidi/tcping?tab=versions).

Go is very picky about versions and requires that v2.x.x versions add `/v2` suffix to the "module" path in the project [go.mod](https://github.com/pouriyajamshidi/tcping/blob/v2.0.0/go.mod).

The [FreeBSD ports framework](https://cgit.freebsd.org/ports/tree/Mk/Uses/go.mk) (and probably others) rely on modules being listed on the Go proxy.

I've implemented a workaround for the FreeBSD port.

**To Reproduce**

1. Go to 'https://pkg.go.dev/github.com/pouriyajamshidi/tcping?tab=versions'
2. Observe that [v2.0.0](https://github.com/pouriyajamshidi/tcping/releases/tag/v2.0.0) is not listed

**Expected behavior**
[v2.0.0](https://github.com/pouriyajamshidi/tcping/releases/tag/v2.0.0) should be listed on the [Go module proxy](https://pkg.go.dev/github.com/pouriyajamshidi/tcping?tab=versions)

- OS: OS agnostic problem
- Browser: Browser agnostic problem
- Version: [v2.0.0](https://github.com/pouriyajamshidi/tcping/releases/tag/v2.0.0)

Credits for debugging: @dmgk

**Comment by pouriyajamshidi** [comment]
Hey @ehaupt,

Whoops! Thanks for reporting this!

Would you care to open a PR for it?

I wonder if it has any effects on anything else other than Go module proxy

**Comment by ehaupt** [comment]
Hi @pouriyajamshidi,

Unfortunately, my plate's pretty full right now and I can't commit to doing a PR.

However, the following post should help with the `/v2` transition of the project: https://go.dev/blog/v2-go-modules

**Comment by pouriyajamshidi** [comment]
Thanks @ehaupt

**Comment by pouriyajamshidi** [comment]
Hi @ehaupt,

The fix is implemented. Let me know if it solves the issue.

**Comment by ehaupt** [comment]
Hi @pouriyajamshidi, thanks for looking into this. This might work. I guess we get the confirmation once you'll tag a new version. If everything is fine it'll be listed on the [proxy](https://pkg.go.dev/github.com/pouriyajamshidi/tcping?tab=versions).

**Comment by pouriyajamshidi** [comment]
Hi @ehaupt,

Thanks. Hopefully we will have a new release soon!

**Comment by pouriyajamshidi** [comment]
Well, this is odd!
Still the version is not picked up by Go packages despite the changes and few releases under v2 flag.

I have looked at some other projects that are `v2` and tcping seems to follow the same approach.

I will mark this as help wanted in hopes of getting some insight from somebody with broader experience with this

**Comment by pouriyajamshidi** [comment]
v2 is not listed on Go module proxy:

https://pkg.go.dev/github.com/pouriyajamshidi/tcping/v2?tab=versions
