### ISSUE TITLE
fix database user input flag

### ISSUE THREAD

**Issue by pouriyajamshidi** [pouriyajamshidi/tcping#131]
## Summary

PR #129 by @wizsk added support for saving reports to the database. However, it is currently not activated due to `permuteArgs` behavior that caused some problem when db name and path was passed by the user.

This issue intends to fix that.

**Comment by wizsk** [comment]
hi @pouriyajamshidi 
Thanks for the mention :smiley:. 
Can you please describe the `func`?

**Comment by pouriyajamshidi** [comment]
Hi @wizsk,

I am willing to hear your proposal to modify the `permuteArgs` func. If it proves to be a small change, we can forfeit moving to Cobra for now and save us some work.

**Comment by wizsk** [comment]
ok @pouriyajamshidi  I will let you know

**Comment by wizsk** [comment]
hey @pouriyajamshidi 
Why can't we do something like this? 
```go

	// arg 1 and 2 is reserved for url and port
	url := os.Args[1]
	port := os.Args[2]

	// we can parse the rest
	os.Args = os.Args[2:]
	flag.Parse()
```
I'm ignoring the error handeling

**Comment by wizsk** [comment]
You want to preserve this functionality 
```go
		{
			"host/ip before option",
			args{args: []string{"127.0.0.1", "8080", "-r", "3"}},
			[]string{"-r", "3", "127.0.0.1", "8080"},
		},
		{
			"host/ip after option",
			args{args: []string{"-r", "3", "127.0.0.1", "8080"}},
			[]string{"-r", "3", "127.0.0.1", "8080"},
		}
```
this is why everything is getting all over the place

**Comment by pouriyajamshidi** [comment]
well, to be frank, that is how all other OS utilities work. The order in which you provide the flags never matters.

**Comment by wizsk** [comment]
got it sorry for over complicating things..

thnaks to @luca-patrignani the issue is resolved

**Comment by pouriyajamshidi** [comment]
> got it sorry for over complicating things..
> 
> thanks to @luca-patrignani the issue is resolved

Not a problem at all mate. I am grateful for your contributions!
