### ISSUE TITLE
Check for updates

### ISSUE THREAD

**Issue by pouriyajamshidi** [pouriyajamshidi/tcping#14]
## Summary

TCPING is constantly being worked on and updated. Our users could benefit from these features.  

We need to check for updates upon running the program and display a message if there is a newer version.

## Important Notes

This should not cause `tcping` to get flagged as a malicious program on `Windows`. If we see this is the case but the benefits of checking for a newer versions exceeds the inconvenience, we might end up splitting the `Windows` version or to just make it an optional flag.

**Comment by icemint0828** [comment]
This is my first time dealing with this type of problem, but I would like to give it a try.
The following is the process I'm considering

* Get release version with go-github package.
* Compare with const version.
* If latest version is exist, print  message to prompt for version up.

What do you think?

P.S.
I become able to use slack!
If you have no problem, please invite me.

icemint0828@gmail.com

**Comment by icemint0828** [comment]
From reading [the Github API documentation](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting), it appears that unauthenticated requests  from the same IP are limited to 60 per hour.

> For unauthenticated requests, the rate limit allows for up to 60 requests per hour. 
> Unauthenticated requests are associated with the originating IP address, and not the person making requests.

If we implement this feature without the flag, users may end up consuming a number of API requests on github every time they run tcping.

Is there any good way to do this?

**Comment by pouriyajamshidi** [comment]
> This is my first time dealing with this type of problem, but I would like to give it a try. The following is the process I'm considering
> 
> * Get release version with go-github package.
> * Compare with const version.
> * If latest version is exist, print  message to prompt for version up.
> 
> What do you think?
> 
> P.S. I become able to use slack! If you have no problem, please invite me.
> 
> [icemint0828@gmail.com](mailto:icemint0828@gmail.com)

Hi,

Your thought process looks fine to me as well.

I am not really familiar with  `go-github` package but it is fine for me. 
I would like to keep our program clean and also as simple as possible. If you notice, I did refactor a lot of things over the weekend as well.

I also contacted you through the email you provided (and removed the email from your comment for privacy reasons).

**Comment by pouriyajamshidi** [comment]
> From reading [the Github API documentation](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting), it appears that unauthenticated requests from the same IP are limited to 60 per hour.
> 
> > For unauthenticated requests, the rate limit allows for up to 60 requests per hour.
> > Unauthenticated requests are associated with the originating IP address, and not the person making requests.
> 
> If we implement this feature without the flag, users may end up consuming a number of API requests on github every time they run tcping.
> 
> Is there any good way to do this?

That is a very valid concern. Let's not automatically do it by default.  
Better to only do it when they actually check for an update.

**Comment by pouriyajamshidi** [comment]
Based on the discussion here, this issue can be ruled out in favor of #15

**Comment by icemint0828** [comment]
Hi.

> Your thought process looks fine to me as well.

Thank you for your opinion!

> That is a very valid concern. Let's not automatically do it by default.

I see.
I'll make sure it's finally implemented that way.

>Better to only do it when they actually check for an update

Yes, I think too. But, I don't have any ideas at the moment.

First, when I implement the update message is displayed without flag, I will put out a PR.

**Comment by pouriyajamshidi** [comment]
> Hi.
> 
> > Your thought process looks fine to me as well.
> 
> Thank you for your opinion!
> 
> > That is a very valid concern. Let's not automatically do it by default.
> 
> I see. I'll make sure it's finally implemented that way.
> 
> > Better to only do it when they actually check for an update
> 
> Yes, I think too. But, I don't have any ideas at the moment.
> 
> First, when I implement the update message is displayed without flag, I will put out a PR.

perfect!
