### ISSUE TITLE
Include db.go in the Makefile

### ISSUE THREAD

**Issue by pouriyajamshidi** [pouriyajamshidi/tcping#142]
## Summary

Currently the Makefile that is used for the build stage is only considering `tcping.go` and `statsprinter.go` as depicted here:

https://github.com/pouriyajamshidi/tcping/blob/9a713aa9bdf7aab16410ea9fc06be0a854d40440/Makefile#L4

Since the program is growing, it is better to just modify that part to include the current directory instead of specifying files one by one.

**Comment by pouriyajamshidi** [comment]
Putting this here for refernce:

https://www.arp242.net/static-go.html

**Comment by wizsk** [comment]
Hi @pouriyajamshidi 

I'm fine. How about you?

https://github.com/pouriyajamshidi/tcping/blob/abf30381952a62682adc5d3280a10f610bcc2aec/Makefile#L42C1-L43C94

Here  while building for CGo is disabled. But sqlite3 uses that. If you build this way the program will run fine but when you will try use use `--db` flag then this err will happen

```bash
~/codes/tcping
❯ GOOS=linux CGO_ENABLED=0 go build -ldflags "-s -w"

~/codes/tcping
❯ ./tcping example.com 80 --db fo.db

Error while writing to the database "fo.db"
err: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub

```

**Comment by pouriyajamshidi** [comment]
Hey @wizsk,

I am also doing well, thanks.

I really appreciate your heads up and explanation.

**Comment by wizsk** [comment]
Hey @pouriyajamshidi 

I'm happy to help.

I looked in the sqlite3 go modules docs but coudn't figure out anything. 

You can look into these:
- https://github.com/mattn/go-sqlite3#compile
- https://github.com/mattn/go-sqlite3#features

I'm not good with compiling stuff. Still learning sorry couldn't help :(

**Comment by wizsk** [comment]
I was able to compile static binary with this.

```bash
# fedora 38
sudo dnf install sqlite-devel sqlite-tcl
sudo dnf install musl-devel musl-gcc
CGO_ENABLED=1 CC=musl-gcc go build --ldflags '-s -w -linkmode external -extldflags=-static'
```

reference: https://gist.github.com/zmb3/2bf29397633c9c9cc5125fdaa988c8a8

**Comment by pouriyajamshidi** [comment]
Thanks a lot @wizsk

**Comment by wizsk** [comment]
You are welcome @pouriyajamshidi

The above method works for linux.

**Comment by pouriyajamshidi** [comment]
I am thinking of possibly ditching the static version since it came about to address an issue when compiling from WSL2.

Nonetheless, when I get some time, I will have a closer look.
