### ISSUE TITLE
refactor the processUserInput function

### ISSUE THREAD

**Issue by pouriyajamshidi** [pouriyajamshidi/tcping#145]
## Summary

The [processUserInput](https://github.com/pouriyajamshidi/tcping/blob/9dda46a7c05e0f5904b1bfb1d7174d90455d5932/tcping.go#L219) function has become a bit lengthy and hard to read. we need to refactor and simplify it a bit to also make the `code factor` happy.

**Comment by friday963** [comment]
Feel free to assign to me if you would, I've already begun.

**Comment by pouriyajamshidi** [comment]
Thanks @friday963

**Comment by friday963** [comment]
Before I spend too much time doing this my own way, do you have a vision for what you'd like to see at its completion?  I had started to re-write with the assumption that I'm NOT re-working a lot of logic.  I'm keeping the logic as you designed it.  However I've been breaking up units of work into methods with the objective of some semblance of single responsibility principle.  

For instance in the case where you've got conflicts between pretty printing and outputting to JSON.  That's a new method that takes your existing logic and just exported it to a func.  Similarly, checking for conflicts between IP (v4/v6) is now a method.

**Comment by friday963** [comment]
Hey @pouriyajamshidi , here's my initial commit.  Added 5 methods to try and consolidate logic where it made sense.

https://github.com/friday963/tcping/blob/update_process_user_input/tcping.go

Just running through commands locally before I do a PR.  Let me know your thoughts.

**Comment by pouriyajamshidi** [comment]
Hey @friday963,

Thanks, I will check it out tomorrow.

**Comment by pouriyajamshidi** [comment]
Hey @friday963,

I had a quick glance and it looks good. Had some minor comments which I will raise when you open a PR.

Thanks

**Comment by pouriyajamshidi** [comment]
Addressed in #149
