### ISSUE TITLE
reduce RTT floating point precision when storing them into the database

### ISSUE THREAD

**Issue by pouriyajamshidi** [pouriyajamshidi/tcping#146]
## Summary

Our new feature to store the stats in a database is **not** following the same floating point precision (**3 points**) when writing the RTT results.

Check out the code here https://github.com/pouriyajamshidi/tcping/blob/9dda46a7c05e0f5904b1bfb1d7174d90455d5932/db.go#L190

We need to convert these similar to:

https://github.com/pouriyajamshidi/tcping/blob/9dda46a7c05e0f5904b1bfb1d7174d90455d5932/statsprinter.go#L457-L461

The conversion may or may not happen in a separate function as long as it does not pollute the current function.

**Comment by wizsk** [comment]
hi @pouriyajamshidi
how are you? 
I will do it.

**Comment by pouriyajamshidi** [comment]
Hi @wizsk,

I am well my friend. How about you?

Thanks a lot

**Comment by wizsk** [comment]
@pouriyajamshidi 

I'm fine too.

I'm happy to help bro :smiley:
