### ISSUE TITLE
Assess replacing current sqlite package

### ISSUE THREAD

**Issue by pouriyajamshidi** [pouriyajamshidi/tcping#152]
## Summary

Currently we are using github.com/mattn/go-sqlite3 for the sqlite3 operations which is not a pure-Go solution and has some shortcomings.

This package https://github.com/zombiezen/go-sqlite is a pure-Go implementation. We should see how much effort it is to migrate to it and if there are any unforeseen challenges.

**Comment by wizsk** [comment]
@pouriyajamshidi 

hey how are you doing? 

I can work on this.

**Comment by pouriyajamshidi** [comment]
Hey @wizsk,

I am doing fine mate. What about you?

Sure. Please go ahead.

I _think_ the Makefile has to be modified as well (I think I made a change in there based on your suggestion to build a static binary. Not quite sure)

**Comment by wizsk** [comment]
@pouriyajamshidi 

I'm doing good.

Ok I will start working.

**Comment by wizsk** [comment]
@pouriyajamshidi 

for 

```sql
CREATE TABLE IF NOT EXISTS people (
    id INTEGER PRIMARY KEY,
    name TEXT,
    age INTEGER,
    time DATETIME
);
```

```go
package main

import (
        "log"
        "time"

        "zombiezen.com/go/sqlite"
)

const timeFormat = "2006-01-02 15:04:05"

func main() {
        conn, err := sqlite.OpenConn("fo.db", sqlite.OpenReadWrite)
        if err != nil {
                log.Fatal(err)
        }
        defer conn.Close()

        insert := "INSERT INTO people (name, age, time) VALUES (?, ?, ?);"
        stmt, err := conn.Prepare(insert)
        if err != nil {
                log.Fatal(err)
        }
        defer stmt.Finalize()

        stmt.BindText(1, "Some name") // you have to insert like this
        stmt.BindInt64(2, 31)
        stmt.BindText(3, time.Now().Format(timeFormat)) // no bindTime method so just use text format
        if _, err = stmt.Step(); err != nil { // flush the change
                log.Fatal(err)
        }
}
```

I was just figuring out how the module woks. 

what do you think should I make the changes?

**Comment by wizsk** [comment]
@pouriyajamshidi open the pr please review it and give some feed back.

**Comment by pouriyajamshidi** [comment]
sure @wizsk 

Thanks!

**Comment by wizsk** [comment]
@pouriyajamshidi 

No worries man.
