### ISSUE TITLE
add time in output line please

### ISSUE THREAD

**Issue by liker5092** [pouriyajamshidi/tcping#215]
as the title !!

**Comment by pouriyajamshidi** [comment]
I am not quite sure if I understand what you need. Please provide an example.

**Comment by liker5092** [comment]
![image](https://github.com/user-attachments/assets/ad601351-edb2-43aa-a27f-75bc9886cbbd)

FYI

display time per line.

**Comment by pouriyajamshidi** [comment]
I'm not sure what value this brings to the tool in general.

The output of `tcping` tries to follow the `ping` utility of Linux.

**Comment by navossoc** [comment]
> I'm not sure what value this brings to the tool in general.
> 
> The output of `tcping` tries to follow the `ping` utility of Linux.

Here it is:

```
       -D
           Print timestamp (unix time + microseconds as in gettimeofday)
           before each line.
````
https://www.man7.org/linux/man-pages/man8/ping.8.html

It is extremely useful if you leave a remote machine being pinged for hours on end and then need to check if there was any loss at a specific time.

The idea is great, I use it a lot, but timestamping with unix time is not very practical, it could even be the default, but it could offer a more human readable format as well.

**Comment by SYSHIL** [comment]
Hii @pouriyajamshidi could I take this up as a first issue?

**Comment by pouriyajamshidi** [comment]
Hi @SYSHIL,

Sure, please go ahead.
