### ISSUE TITLE
[Research] Switch to `ParseAddr` in net/ip library

### ISSUE THREAD

**Issue by pouriyajamshidi** [pouriyajamshidi/tcping#22]
## Description

We are currently using `ParseIP` from `net` library to parse the IP address https://github.com/pouriyajamshidi/tcping/blob/9478b2c8610172f322b9d84b5936d7167dbd92b2/tcping.go#L228   

Go 18 introduced `ParseAddr` in [net/ip](https://pkg.go.dev/net/netip#ParseAddr) standard library. We need to investigate and see if it is beneficial to switch to `ParseAddr`  instead.  

If `ParseAddr` is not providing any additional benefits to us, we can close this ticket.

**Comment by segfault99** [comment]
Hello.
The advantages of the netip package I have  noticed  for this project are;
- Unlike net.IP or net.IPAddr, netip.Addr is a comparable value type (it supports == and can be a map key) and is immutable.
- You can distinguish between IPv4 and IPv6 address types.
There are also other advantages like smaller memory footprint, zero heap allocation etc. which could be meaningful in case of excessive usage of IPs.

**Comment by pouriyajamshidi** [comment]
Hi @segfault99 ,

Thank you for bringing this to our attention! If you like, you are welcome to contribute to our project and take up on the ticket.

**Comment by pouriyajamshidi** [comment]
Addressed in https://github.com/pouriyajamshidi/tcping/pull/41
