### ISSUE TITLE
Dockerize TCPING

### ISSUE THREAD

**Issue by pouriyajamshidi** [pouriyajamshidi/tcping#23]
# Summary

We need to have a very lightweight Docker container hosting `tcping` to provide more convenience for our users.

This should account for an easy or automated way to update the container image with each new `tcping` release.

> ⚠️  **Alpine Linux should not be used**

**Comment by SergeyParamoshkin** [comment]
@pouriyajamshidi Hi, need Dockerfile for build or using ?

**Comment by pouriyajamshidi** [comment]
> @pouriyajamshidi Hi, need Dockerfile for build or using ?

Hi @SergeyParamoshkin,

A Docker container. It should be used similar to having binaries in your PATH. i.e:

```bash
tcping example.com 443
```

should use the Docker container.

**Comment by SergeyParamoshkin** [comment]
> > @pouriyajamshidi Hi, need Dockerfile for build or using ?
> 
> Hi @SergeyParamoshkin,
> 
> A Docker container. It should be used similar to having binaries in your PATH. i.e:
> 
> ```shell
> tcping example.com 443
> ```
> 
> this command should use the Docker container.
```
$ docker run -ti --rm tcping:develop www.example.com 443                                                                                       
TCPinging www.example.com on port 443
Reply from www.example.com (93.184.216.34) on port 443 TCP_conn=1 time=124 ms
Reply from www.example.com (93.184.216.34) on port 443 TCP_conn=2 time=133 ms
Reply from www.example.com (93.184.216.34) on port 443 TCP_conn=3 time=129 ms
^C
--- www.example.com TCPing statistics ---
3 probes transmitted, 3 received, 0.00% packet loss
successful probes:   3
unsuccessful probes: 0
last successful probe:   2022-06-18 20:36:10
last unsuccessful probe: Never failed
total uptime:   3 seconds
total downtime: 0 second
longest uptime:   3 seconds from 2022-06-18 20:36:08 to 2022-06-18 20:36:10
Retried to resolve hostname 0 times
rtt min/avg/max: 124/128.67/133 ms
--------------------------------------
TCPing started at: 2022-06-18 20:36:08
TCPing ended at:   2022-06-18 20:36:11
duration (HH:MM:SS): 00:00:02
```

**Comment by pouriyajamshidi** [comment]
Addressed in https://github.com/pouriyajamshidi/tcping/commit/6cbbb86b475d011bcfa3c495020db06f6e7434c0
