### ISSUE TITLE
Add tests for outputting information to stdout 

### ISSUE THREAD

**Issue by pouriyajamshidi** [pouriyajamshidi/tcping#232]
## Summary

We have quite a handful of tests covering various aspects of the tool. However, one of the most crucial components of what tcping offers is not tested: 

- writing information to `STDOUT`

In the past, we have had PRs that unwantedly changed the way tcping displays information in the terminal.

We would like to have some tests to ensure the **intended fields** are displayed as per the provided flags by the user.

For instance, given the `-D` flag, the timestamp field should be present or in all cases, the `time` field (TTL in the code) should be there.

Any other tests improving the existing ones is also more than welcome

**Comment by basil-gray** [comment]
@pouriyajamshidi Hello, I would love to work on this.

**Comment by basil-gray** [comment]
By the way, I don't see any reference to a -d flag that prints the TTL, only RTT?

I'll add a test for pings for now.

**Comment by pouriyajamshidi** [comment]
Hi @basil-gray 

Thank you for the interest and willing to help. I will assign this to you then.

> By the way, I don't see any reference to a -d flag that prints the TTL, only RTT?

The `-D` flag is to print the timestamps and it is not yet released.

RTT is defined here:

https://github.com/pouriyajamshidi/tcping/blob/ea495b0d18d287a9352b0564c30ef118774bd6f9/tcping.go#L90

which is displayed as `time=ab.xyz` in the console output. The code is here:

https://github.com/pouriyajamshidi/tcping/blob/ea495b0d18d287a9352b0564c30ef118774bd6f9/statsprinter.go#L167

**Comment by basil-gray** [comment]
Just to update: still working on this! Life's been busy.

**Comment by pouriyajamshidi** [comment]
> Just to update: still working on this! Life's been busy.

Thank you for the update. No worries at all.

**Comment by basil-gray** [comment]
I just put up #237.

It adds tests for TestPrintProbeSuccess and TestPrintProbeFail to check that the formatting and colors of stdout are as expected. I don't have time to figure out how to check for the presence of flags right now, so I'll let you decide where to make a separate issue for that or to keep this one open :)

**Comment by pouriyajamshidi** [comment]
Thanks @basil-gray 
I will have a look 

the latter is fine to be done in another issue

**Comment by basil-gray** [comment]
Hm. The tests pass locally, but the color data doesn't seem to be writing to stdout on the test runner. It's failing my tests where I'm using ANSI escape codes for the expected result. 

Do we need to test the colors too, or is just the content fine?

**Comment by pouriyajamshidi** [comment]
No need to test the colors.
