### ISSUE TITLE
SQLite Output Fails with hyphens in hostname

### ISSUE THREAD

**Issue by andywhitaker** [pouriyajamshidi/tcping#239]
It appears I get a failure when outputting to db if the server hostname includes a hyphen. I encountered while testing a site but was able to reproduce with a minimal example by creating two hostfile entries to localhost and running a lightweight server locally:

Hostnames:
- testserver
- test-server

Working example pinging "testserver" on port 8000:

```
tcping testserver 8000 --db ./testserver.db
TCPinging testserver on port 8000
^C
Statistics for "testserver" have been saved to "./testserver.db" in the table "testserver_8000_10_53_11_10_05_2024"
```

Failing example pinging "test-server" on port 8000:

```
tcping test-server 8000 --db ./testserver.db

Error writing to the database "./testserver.db"
err: sqlite: prepare "\n-- Organized row names together for better readability\nCREATE TABLE test-server_8000_10_49_06_10_05_2024 (\n    id INTEGER PRIMARY KEY,\n    event_type TEXT NOT NULL, -- for the data type eg. statistics, hostname change\n    timestamp DATETIME,\n    addr TEXT,\n    hostname TEXT,\n    port INTEGER,\n    hostname_resolve_retries INTEGER,\n\n    hostname_changed_to TEXT,\n    hostname_change_time DATETIME,\n\n    latency_min REAL,\n    latency_avg REAL,\n    latency_max REAL,\n\n\ttotal_duration TEXT,\n    start_time DATETIME,\n    end_time DATETIME,\n\n\tnever_succeed_probe INTEGER, -- value will be 1 if a probe never succeeded\n\tnever_failed_probe INTEGER, -- value will be 1 if a probe never failed\n    last_successful_probe DATETIME,\n    last_unsuccessful_probe DATETIME,\n\n    longest_uptime TEXT,\n    longest_uptime_start DATETIME,\n    longest_uptime_end DATETIME,\n\n    longest_downtime TEXT,\n    longest_downtime_start DATETIME,\n    longest_downtime_end DATETIME,\n\n    total_packets INTEGER,\n    total_packet_loss REAL,\n    total_successful_probes INTEGER,\n    total_unsuccessful_probes INTEGER,\n\n    total_uptime TEXT,\n    total_downtime TEXT\n);": 3:18: SQL logic error: near "-": syntax error
```

Thanks!

**Comment by pouriyajamshidi** [comment]
Hi @andywhitaker 

Thanks for reporting this. We will get it fixed.

**Comment by pro0o** [comment]
Hello @pouriyajamshidi,
has the issue been resolved? If not, my guess on fixing it: sanitizing and properly escaping table names in query.
I'd be happy to work on it as my first contribution. Any guidance would be much appreciated!

**Comment by pouriyajamshidi** [comment]
Hi @pro0o,

This is not resolved. You are more than welcome to work on it. Basically what you have mentioned should fix it.

Thanks in advance!

**Comment by pro0o** [comment]
as far as i can think of, these are the possible fixes to this bug:
1. replacing hyphens with underscores
2. quoting table names with hyphens

The first option seems better as it simplifies the process and reduces SQL injection risk while keeping the original hostnames. while The second option adds unnecessary complexity i guess.

here's the possible change in  [db.go](https://github.com/pouriyajamshidi/tcping/blob/master/db.go#L120): 
```go
// newTableName generates a sanitized table name based on the hostname and port.
// It replaces '.' and '-' with '_' to ensure the table name is valid in SQLite.
// The table name format: "hostname_port_hour_minute_sec_day_month_year"
func newTableName(args []string) string {
	// Replace '.' and '-' with '_' in the hostname to sanitize the table name
	sanitizedHost := strings.ReplaceAll(args[0], ".", "_")
	sanitizedHost = strings.ReplaceAll(sanitizedHost, "-", "_") // Replace hyphens with underscores

	tableName := fmt.Sprintf("%s_%s_%s", sanitizedHost, args[1], time.Now().Format("15_04_05_01_02_2006"))
	if unicode.IsNumber(rune(tableName[0])) {
		tableName = "_" + tableName
	}

	return tableName
}
````
![image](https://github.com/user-attachments/assets/b702a2ef-8cb1-4de3-8fb5-f88372b6935e)


@pouriyajamshidi

**Comment by pouriyajamshidi** [comment]
I would keep it simple. Replacing `-` with `_` is fine.

Not sure why you are also replacing the `.`s. Where could that be an issue?

**Comment by pro0o** [comment]
![image](https://github.com/user-attachments/assets/6f28a61a-2a48-4e14-964c-610eeb39ae14)
welp, indeed "." is misinterpreted too.

**Comment by pouriyajamshidi** [comment]
huh, that is strange!

I don't think I faced that before. Does it behave the same with IP addresses too?

**Comment by pro0o** [comment]
yupp
> I don't think I faced that before. Does it behave the same with IP addresses too?

**Comment by pouriyajamshidi** [comment]
not sure how you are getting a failure for IP addresses. Works for me

![image](https://github.com/user-attachments/assets/7d6a5bd0-e835-45ca-a35a-91e00ed28012)

**Comment by pro0o** [comment]
well, the replacement of "." with "_" was already there in the [db.go](https://github.com/pouriyajamshidi/tcping/blob/master/db.go#L120) lol.
should i just change the hyphen to underscores, it should fix the hyphen bug.

**Comment by pro0o** [comment]
> not sure how you are getting a failure for IP addresses. Works for me
> 
> ![image](https://private-user-images.githubusercontent.com/54482226/377140857-7d6a5bd0-e835-45ca-a35a-91e00ed28012.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwOTc3MjIsIm5iZiI6MTcyOTA5NzQyMiwicGF0aCI6Ii81NDQ4MjIyNi8zNzcxNDA4NTctN2Q2YTViZDAtZTgzNS00NWNhLWEzNWEtOTFlMDBlZDI4MDEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDE2NTAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmMWMwNzNiNDZjMTUwZDRkNWRkMWFmZjdlNmI2MjFhYmU2NDg2ODZjYmE2MjYzMTNjZTAzMTQ1ZjE0Mjc0ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LwXLx7uiWCztFhyHgCGlZkdVAHnoZylABxlwIBW_Mmk)

so the reason it was not working was i didn't replaced the "." with "_".

**Comment by pouriyajamshidi** [comment]
> well, the replacement of "." with "_" was already there in the [db.go](https://github.com/pouriyajamshidi/tcping/blob/master/db.go#L124) lol. should i just change the hyphen to underscores, it should fix the hyphen bug.

yes, please
