### ISSUE TITLE
Weirdness in Makefile causes difficulty when packaging for non-Debian distros

### ISSUE THREAD

**Issue by cyqsimon** [pouriyajamshidi/tcping#242]
First of all, thanks for the excellent software. In my personal opinion, this is the best implementation of this functionality I've seen so far.

I have packaged this tool [on COPR](https://copr.fedorainfracloud.org/coprs/cyqsimon/tcping-go/) a while back. In the recently released v2.6.0, I saw that `Makefile` now includes split targets, so I thought it'd be a good idea to use them. In particular, `build_linux_static` seems like the most useful one for me.

However to my surprise, this target calls `make build_debian_package`, which uses `dpkg-deb`. Obviously this is not useful on non-Debian-based distros, and is usually not installed by default (or even available) on them. Fedora and RHEL (which I'm targeting on COPR) are premier examples.

It seems to me that the dependency relation is inverted here: `build_linux_static` could be useful in lots of circumstances, and there's no reason why it ***has to*** build a `.deb` in the process. Can you please consider reorganising this a bit? Thanks.

**Comment by pouriyajamshidi** [comment]
Hi @cyqsimon 

Thanks for the kind words and the info!

Yea, sounds reasonable. Would you be willing to open a PR for this?

Otherwise, I will get to it some time next week. Life is very busy at the moment.

**Comment by cyqsimon** [comment]
> Would you be willing to open a PR for this?

Yeah will give it a go. I was a bit concerned about breaking existing workflows but on second thought, it's probably not that serious.
