### ISSUE TITLE
TCP client port number displayed in output like psping it helps in filtering multi-point capture

### ISSUE THREAD

**Issue by rishdas** [pouriyajamshidi/tcping#249]
![image](https://github.com/user-attachments/assets/1f221383-a9e5-4fcf-a00e-1ed6c0e48ddb)

**Comment by pouriyajamshidi** [comment]
Addressed in https://github.com/pouriyajamshidi/tcping/pull/263

you can compile from source or use `go install` till we officially release version 2.7.0
