### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by conanlm** [pouriyajamshidi/tcping#259]
x509: certificate signed by unknown authority

Can we trust it directly
![lx_clip1731308480425](https://github.com/user-attachments/assets/396bb7fc-86e5-4e4d-9185-9806d0fe17ab)

**Comment by pouriyajamshidi** [comment]
Hey @conanlm,

The image you shared shows a different tcping utility. We do not do http(s) yet.

**Comment by conanlm** [comment]
sorry

**Comment by pouriyajamshidi** [comment]
no worries
