### ISSUE TITLE
Make a logo for TCPING

### ISSUE THREAD

**Issue by pouriyajamshidi** [pouriyajamshidi/tcping#26]
# Summary

We are at a stage that many people are using this software yet we don't have a logo :).

If anyone has the capabilities to make one, we greatly appreciate it.

**Comment by code-hyker** [comment]
Hey @pouriyajamshidi may I work on this?

**Comment by pouriyajamshidi** [comment]
> Hey @pouriyajamshidi may I work on this?

Hi @code-hyker ,

That would be awesome! Thank you.

**Comment by code-hyker** [comment]
Can you tell me in what format you want it ,  an HTML file(using HTML+CSS)  or just a picture with .jpg or .png extension?

**Comment by pouriyajamshidi** [comment]
> Can you tell me in what format you want it , an HTML file(using HTML+CSS) or just a picture with .jpg or .png extension?

If it is possible for you, HTML + CSS and PNG (so in the future we can modify it if it is necessary). Otherwise, PNG is enough.

**Comment by code-hyker** [comment]
Alright.

**Comment by pouriyajamshidi** [comment]
In your PR you could also put them in a directory called `Artwork`.

Thanks!

**Comment by code-hyker** [comment]
Do I need to create a directory called Artwork ? If yes,I will put both HTML file and a picture in it.

**Comment by code-hyker** [comment]
ASSIGN ME THE TASK FIRST!

**Comment by pouriyajamshidi** [comment]
> Do I need to create a directory called Artwork ? If yes,I will put both HTML file and a picture in it.

yes please.

**Comment by code-hyker** [comment]
Okay!

**Comment by code-hyker** [comment]
@pouriyajamshidi When I am trying to upload the logo.html file from my PC it says I don't have the push access

**Comment by pouriyajamshidi** [comment]
> @pouriyajamshidi When I am trying to upload the logo.html file from my PC it says I don't have the push access

You need to push it up into your fork of this project and then open a PR. Pushing to this project directly is not possible.

**Comment by code-hyker** [comment]
DONE !

**Comment by pouriyajamshidi** [comment]
> DONE !

I don't see the PR yet?

**Comment by code-hyker** [comment]
I have created and sent  from my own fork.

**Comment by code-hyker** [comment]
Did you get it?

**Comment by code-hyker** [comment]
Acknowledge me about it.

**Comment by pouriyajamshidi** [comment]
I have received your PR but it was closed a few minutes ago. Was that intentional?

**Comment by code-hyker** [comment]
Yeah,it was intentional . I have sent a new PR.

**Comment by pouriyajamshidi** [comment]
for the record, to make sure your PR has been received and viewable by me, you can check here https://github.com/pouriyajamshidi/tcping/pulls

**Comment by code-hyker** [comment]
Yeah sure !
Is the logo okay?

**Comment by pouriyajamshidi** [comment]
> Yeah sure ! Is the logo okay?

In overall, yes. However, it would be way nicer if it could include the name of the project in it (`tcping`) to provide some resemblance for people who see it without having to put too much thinking into it.

**Comment by code-hyker** [comment]
Alright . I will do so.

**Comment by pouriyajamshidi** [comment]
thank you for your time and efforts

**Comment by code-hyker** [comment]
I have made the necessary changes in the logo.png file.So delete the first one as it is useless

**Comment by pouriyajamshidi** [comment]
> I have made the necessary changes in the logo.png file.So delete the first one as it is useless

You can just replace the image in you PR. This way, there is no need to open a PR to delete a file. one PR is enough to get to the end result. I will close the most recent one you opened.

**Comment by code-hyker** [comment]
So should I close the second PR for convenience?

**Comment by pouriyajamshidi** [comment]
It is fine. Your logo is in now. Thanks
