### ISSUE TITLE
Following `go install` installation instructions install (old) v1.22.1

### ISSUE THREAD

**Issue by toadjaune** [pouriyajamshidi/tcping#262]
Hi there !

That's a pretty cool project, thanks for making this ! :D

**Describe the bug**

When following the `go install` instructions in the README, version `v1.22.1` gets installed, instead of the latest `v2.x`.

**To Reproduce**

```
$ go install github.com/pouriyajamshidi/tcping@latest
go: downloading github.com/pouriyajamshidi/tcping v1.22.1
go: downloading github.com/gookit/color v1.5.3
go: downloading github.com/google/go-github/v45 v45.2.0
go: downloading github.com/xo/terminfo v0.0.0-20220910002029-abceb7e1c41e
go: downloading golang.org/x/crypto v0.9.0
go: downloading github.com/google/go-querystring v1.1.0

$ tcping version

TCPING version 1.21.2
[...]
```

**Expected behavior**
`tcping version` would return a `2.x` version (either the lastest point release or the `master` branch, I don't know)

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: Fedora 40 (Workstation)
- Browser: N/A
- Version: N/A
- go version : `go version go1.22.7 linux/amd64`

**Additional context**
N/A

**Comment by pouriyajamshidi** [comment]
Hi @toadjaune,

Thank you for the kind words and reporting this issue!

Will get it fixed.

**Comment by toadjaune** [comment]
Thanks for the quick response !

Don't hesitate to let me know if you can't reproduce and/or need me to run any test on my end !

**Comment by toadjaune** [comment]
```shell
$ go install github.com/pouriyajamshidi/tcping/v2@latest
go: downloading github.com/pouriyajamshidi/tcping v1.22.1
go: downloading github.com/pouriyajamshidi/tcping/v2 v2.6.0
go: github.com/pouriyajamshidi/tcping/v2@latest: github.com/pouriyajamshidi/tcping/v2@v2.6.0 requires go >= 1.23.1 (running go 1.22.7; GOTOOLCHAIN=local)

$ go install github.com/pouriyajamshidi/tcping@2.6.0
go: github.com/pouriyajamshidi/tcping@2.6.0: github.com/pouriyajamshidi/tcping@2.6.0: invalid version: unknown revision 2.6.0
```
As you may have guessed, neither command installs tcping.

I'm assuming the first one would work if my system go was newer.

**Comment by pouriyajamshidi** [comment]
ok, cool. I also did some tests:

In version `1.23.3`

```bash
TheGrayNode.io> docker run --rm -it golang:1.23.3 /bin/bash
root@go_1.23.3:/go# go install github.com/pouriyajamshidi/tcping@latest
go: downloading github.com/pouriyajamshidi/tcping v1.22.1
root@go_1.23.3:/go# 
root@go_1.23.3:/go# 
root@go_1.23.3:/go# go install github.com/pouriyajamshidi/tcping/v2@latest
go: downloading github.com/pouriyajamshidi/tcping/v2 v2.6.0
root@go_1.23.3:/go#
```

And in version `1.22.3`

```bash
TheGrayNode.io> docker run --rm -it golang:1.22.3 /bin/bash
root@1.22.3:/go# go install github.com/pouriyajamshidi/tcping/v2@latest
go: downloading github.com/pouriyajamshidi/tcping v1.22.1
go: downloading github.com/pouriyajamshidi/tcping/v2 v2.6.0
go: github.com/pouriyajamshidi/tcping/v2@latest: github.com/pouriyajamshidi/tcping/v2@v2.6.0 requires go >= 1.23.1 (running go 1.22.3; GOTOOLCHAIN=local)
root@1.22.3:/go# 
```

I can confirm two things:

1. the command should be `go install github.com/pouriyajamshidi/tcping/v2@latest`
2. if your Go version is lower than the intended one here, you get the older version.

In regards to the Go version, there is not much we can do but the README file needs some updating to point to the correct URL and also perhaps mention the Go version.

Would you feel comfortable to open a PR for this?
Since you have reported this and helped identifying it, it would be nice to have your name as one of the contributors.

**Comment by toadjaune** [comment]
Gladly :)
