### ISSUE TITLE
update the Chinese README file

### ISSUE THREAD

**Issue by pouriyajamshidi** [pouriyajamshidi/tcping#265]
## Summary

The README file has been updated here https://github.com/pouriyajamshidi/tcping/commit/b3d7590fd0817f5780167a5a9557c4abb4a8af69,

here https://github.com/pouriyajamshidi/tcping/blob/b3d7590fd0817f5780167a5a9557c4abb4a8af69/README.md?plain=1#L256 

and here https://github.com/pouriyajamshidi/tcping/blob/b3d7590fd0817f5780167a5a9557c4abb4a8af69/README.md?plain=1#L261

and the Chinese version lacks these explanations.

**Comment by pouriyajamshidi** [comment]
Hi @edwinjhlee 

Would you be willing to help on this?

**Comment by edwinjhlee** [comment]
Of course ~ @pouriyajamshidi

**Comment by pouriyajamshidi** [comment]
Thank you so much @edwinjhlee
