### ISSUE TITLE
Execution in xshell looks like this, thank you

### ISSUE THREAD

**Issue by HeliusHao** [pouriyajamshidi/tcping#275]
![Snipaste_2024-12-24_10-55-05](https://github.com/user-attachments/assets/e6b47961-33d9-47ec-bd26-adf1a93d5cf9)

**Comment by pouriyajamshidi** [comment]
Hey @HeliusHao,

Thanks for reporting this.

I am not familiar with xshell myself, and this is the first time hearing about it. As for tcping, I have used it in a lot of different terminal emulators without any issues.

This could be an xshell problem. Let me ask you a few questions.

- Is it the latest version of xshell?
- Does this happen in fullscreen mode?
- The IP address seems to be highlighted either by you or automatically. Will this happen without the highlight too?

**Comment by pouriyajamshidi** [comment]
Ok, I was able to reproduce this.

Apparently, Xshell has a default shell to spawn other shells, and this is where things go wrong.

![image](https://github.com/user-attachments/assets/5d137532-b64c-4163-bd2b-e819b2835594)


However, if you spin a proper shell, say CMD, Bash, or SSH to another machine, it displays it correctly:

![image](https://github.com/user-attachments/assets/2a36e224-6bd1-46f8-8978-ea99afa23f6c)


I do not see this as a tcping problem, rather a weirdness in Xshell.
