### ISSUE TITLE
Add Arm64 support

### ISSUE THREAD

**Issue by pouriyajamshidi** [pouriyajamshidi/tcping#35]
## Summary

With the rise of Arm chips, we should also add the binaries for those. 

We need:

1. Linux Arm64
2. Apple Arm64

This should be instructed inside our `Makefile`.

Please make sure to test this and make sure the binaries work before submitting a PR.

**Comment by ChrisClarke246** [comment]
Hey @pouriyajamshidi is this issue still open?

**Comment by pouriyajamshidi** [comment]
Thanks @ChrisClarke246 
Best of luck mate
