### ISSUE TITLE
Fix GitHub Actions workflows

### ISSUE THREAD

**Issue by pouriyajamshidi** [pouriyajamshidi/tcping#38]
## Summary

There are a few shortcomings in the current workflows and the goal of this ticket is to fix these issues:

1. Go version is not being picked up by the CI system
2. Docker images are not being tagged. This used to work before

**Comment by ahmednreldin** [comment]
can you enable 
Run workflows from fork pull requests from Settings of actions 
so that i can solve the issue

**Comment by pouriyajamshidi** [comment]
> can you enable Run workflows from fork pull requests from Settings of actions so that i can solve the issue

Hi and thanks for offering a hand.

I will enable it shortly.

**Comment by pouriyajamshidi** [comment]
There is no setting available for me to do it globally. The best thing I could find that applies to this repo is discussed here:

https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks

**Comment by ahmednreldin** [comment]
i have made a tiny change, can you try now picking of go version

**Comment by pouriyajamshidi** [comment]
thanks for your contribution.
