### ISSUE TITLE
 Retry resolving target's hostname after a certain number of failed requests

### ISSUE THREAD

**Issue by pouriyajamshidi** [pouriyajamshidi/tcping#4]
## Summary

If a hostname is given, it could be beneficial to retry resolving it after a certain amount of probe failures since `tcping` could be used to check and analyze Anycast sites. However automatically doing this might yield undesirable results.  

It could be better to introduce a flag to give users control.

**Comment by icemint0828** [comment]
I'd like take up this issue.

**Comment by icemint0828** [comment]
Hi, @pouriyajamshidi.
Can I change format of tcping args to like below?

`tcping -h <hostname/ip> -p <port number> -r`
or
`tcping -h <hostname/ip> -p <port number>`

Beacause, more arguments may be specified in the future as far as I read other Issues.
If it is not a problem, I will use the flag package.

**Comment by pouriyajamshidi** [comment]
Hi @icemint0828 ,

Thanks for your contributions. It is more than ok to do so. However, please note that `tcping` still has to work similar to what it does now, without specifying the flags. Like the `ping` utility.

**Comment by icemint0828** [comment]
@pouriyajamshidi 
Ok, I see.
The work will be divided into two phases.

* Replacement with the flag package
* Add flag to retry resolving target's hostname

**Comment by icemint0828** [comment]
> `tcping -h <hostname/ip> -p <port number>`

I change to below in #13.

`tcping <hostname/ip> -p <port number>`

I think it is better form.

**Comment by pouriyajamshidi** [comment]
> > `tcping -h <hostname/ip> -p <port number>`
> 
> I change to below in #13.
> 
> `tcping <hostname/ip> -p <port number>`
> 
> I think it is better form.

Hi, left my comment there.
thanks!
