### ISSUE TITLE
DNS resolver does not account for timing

### ISSUE THREAD

**Issue by pouriyajamshidi** [pouriyajamshidi/tcping#40]
## Summary

Upon specifying the `-r` flag, the `retryResolve` function is called whenever there is a need to resolve the hostname again. This can be useful when the target is geographically distributed and when there are GSLBs involved. The function is defined here: https://github.com/pouriyajamshidi/tcping/blob/2464548e1a5e59a0e172461ff3e31692d26c26e1/tcping.go#L262

### Problem

The function does not account for timing. For instance, when the internet connection is down, this function takes 4~5 seconds to timeout while nothing gets added to the respective timers here:

https://github.com/pouriyajamshidi/tcping/blob/2464548e1a5e59a0e172461ff3e31692d26c26e1/tcping.go#L415-L418

## Solution

The `retryResolve` function needs to control and add to those timers as well.

**Comment by sonarypt** [comment]
After virtualized a webserver for demo, I still cannot simulate any situation when that function takes 4~5 seconds to timeout. Could you give more information for that scenario?

**Comment by sonarypt** [comment]
Uhm, I tried your scenario on my machine (Arch Linux - amd64 - go1.18.4). Previously using wifi, I disconnected my internet access by command `nmcli radio wifi off`. I also add line into `printRetryingToResolve()` that print out total down time to the terminal. Eventually, `retrying to resolve` does not take any extra second to timeout. Everything seems to be smooth.

**Comment by pouriyajamshidi** [comment]
yea, I also tried again and I don't see any hiccups like before. Now I wonder how it had occurred. Because it was the reason to open a ticket for it.

Let's try some more and if it does not occur again, we can close this for now.

**Comment by pouriyajamshidi** [comment]
@t-ohtaki do you know a situation which this can be triggered?

**Comment by icemint0828** [comment]
@pouriyajamshidi 
I can see the event happening with the procedure that pouriya mentioned (tcping example.com 443 -r 2 and wifi on/off).

![スクリーンショット 2022-07-22 12 11 44](https://user-images.githubusercontent.com/89819001/180355116-8712d7fd-8ddb-4010-9d2f-4aa4031f30c5.png)

**Comment by pouriyajamshidi** [comment]
Thanks a lot @icemint0828. Helpful as always.

I hope this clears the issue @sonarypt
