### ISSUE TITLE
Add Linux binary installation into Brew tap

### ISSUE THREAD

**Issue by yermulnik** [pouriyajamshidi/tcping#47]
**Is your feature request related to a problem? Please describe.**
Can't install `tcping` on Linux using Homebrew despite having Linux binaries and Homebrew supporting Linux.

**Describe the solution you'd like**
Add Linux binaries to Homebrew tap.

**Describe alternatives you've considered**
Homebrew is a great package manager support on Linux too.

**Comment by pouriyajamshidi** [comment]
Hey @yermulnik ,

Thanks for bringing this to my attention.

I have no experience with brew and Linux but I will try to take a look this weekend.

**Comment by pouriyajamshidi** [comment]
Could you try with the command below and let me know if it is working now?

```bash
brew install pouriyajamshidi/tap/linux_tcping
```

Thanks in advance

**Comment by yermulnik** [comment]
@pouriyajamshidi Thanks for looking into this.
I tried and it failed:
```bash
> brew install pouriyajamshidi/tap/linux_tcping
Error: No available formula with the name "pouriyajamshidi/tap/linux_tcping". Did you mean pouriyajamshidi/tap/tcping?
In formula file: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/pouriyajamshidi/homebrew-tap/linux_tcping.rb
Expected to find class LinuxTcping, but only found: Tcping.
```

As for tap you don't actually need a standalone tap for Linux, but rather just add Linux binaries into existing one. Here are some examples from custom tap I have installed locally:
* https://github.com/peak/homebrew-tap/blob/main/Formula/s5cmd.rb
* https://github.com/env0/homebrew-terratag/blob/master/terratag.rb
* https://github.com/hashicorp/homebrew-tap/tree/master/Formula

Hope this helps.

Also what I've found when initially installed `tcping` (which obviously installed MacOS binary) was that the binary was missing executable bit. Not sure whether it's okay for Homebrew on MacOS though 🤷🏻 
```bash
> brew install pouriyajamshidi/tap/tcping
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).

==> Downloading https://github.com/pouriyajamshidi/tcping/releases/download/v1.12.1/tcping_MacOS.zip
Already downloaded: /home/giermulnik/.cache/Homebrew/downloads/61d79fbc1b1230f95ba15d9b1029d53cded82d392f373a4775acc3c906e6f6e5--tcping_MacOS.zip
==> Installing tcping from pouriyajamshidi/tap
✔  /home/linuxbrew/.linuxbrew/Cellar/tcping/v1.12.1: 3 files, 5.3MB, built in 1 second
==> Running `brew cleanup tcping`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).

> ls -la /home/linuxbrew/.linuxbrew/Cellar/tcping/v1.12.1/bin/tcping
-r--r--r-- 1 giermulnik giermulnik 5509968 Jul 10 23:13 /home/linuxbrew/.linuxbrew/Cellar/tcping/v1.12.1/bin/tcping

> ls -la /home/linuxbrew/.linuxbrew/bin/tcping
lrwxrwxrwx 1 giermulnik giermulnik 35 Nov 19 16:45 /home/linuxbrew/.linuxbrew/bin/tcping -> ../Cellar/tcping/v1.12.1/bin/tcping
```

**Comment by pouriyajamshidi** [comment]
Hey @yermulnik,

Thank you so much for providing those examples. I have made the necessary changes and it should be ok now. Though I am not having my Linux machine to test it myself now, so I will rely on your update to give it an ok or not.

Regarding the Mac OS binary, not having the `x` bit is fine. It works as expected.

**Comment by yermulnik** [comment]
All good! Thanks a lot!
```bash
> brew install pouriyajamshidi/tap/tcping
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).

==> Downloading https://github.com/pouriyajamshidi/tcping/releases/download/v1.12.1/tcping_Linux.zip
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/34
######################################################################## 100.0%
==> Installing tcping from pouriyajamshidi/tap
✔  /home/linuxbrew/.linuxbrew/Cellar/tcping/v1.12.1: 3 files, 5MB, built in 3 seconds
==> Running `brew cleanup tcping`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).

> which tcping
/home/linuxbrew/.linuxbrew/bin/tcping

> tcping -v
TCPING version 1.12.1
```

**Comment by pouriyajamshidi** [comment]
Perfect! Thanks!
