### ISSUE TITLE
Show longest uptime

### ISSUE THREAD

**Issue by pouriyajamshidi** [pouriyajamshidi/tcping#5]
## Summary

Currently the longest downtime is shown in the reports. It could be a nice feature to show the longest uptime as well.

**Comment by icemint0828** [comment]
I'd like take up this issue.

But can I refactor the longestDowntime structure before doing so?
Specifically, I would like to do the following, and use for longest uptime too.

```
type longestTime struct {
	start    time.Time
	end      time.Time
	duration float64
}

func newLongestTime(startTime , endTime time.Time) longestTime {
	return longestTime{
		start:    startTime,
		end:      endTime,
		duration: endTime.Sub(startTime).Seconds(),
	}
}
```

Is it okay?

**Comment by pouriyajamshidi** [comment]
More than ok. Please go ahead! 

Thanks.
