### ISSUE TITLE
Increase RTT resolution/verbosity

### ISSUE THREAD

**Issue by m-kratochvil** [pouriyajamshidi/tcping#54]
First of all, this is a very useful tool, thank you for creating it and keeping it updated.

I'd like to ask to implement the `time=` resolution up to a microsecond resolution.
Currently, the report shows as follows:
![tcping_time](https://user-images.githubusercontent.com/43531504/216581565-77b1d57f-d193-444f-a41b-3cadcbe596c7.JPG)

What I'd love to see is the report show more verbose time, like this:
```
Reply from 10.180.1.248 on port 80 TCP_conn=2 time=0.253 ms
```
I am using the tool in a datacenter environment where the RTT times are usually sub-millisecond and if I'd be able to see such times, it would greatly expand the usefulness of tcping in DC troubleshooting / testing scenarios.

Thank you for considering this.

**Comment by pouriyajamshidi** [comment]
Hi @m-kratochvil,

Thanks for the kind words.

Indeed, this is a shortcoming that I am aware of and it was on my radar for a while. The reason it has not been implemented yet is, this small change requires a lot of refactoring and addressing technical debt.

Fun fact, I created this tool to address a problem we had for WAN interfaces in a few data centers we were managing. Although the LAN side as you mentioned requires a sub ms second calculations.

Having said that, I will definitely implement it in the near (hopefully) future and also welcome PRs from the community.

**Comment by pouriyajamshidi** [comment]
Hey @m-kratochvil,

I have implemented the sub-millisecond reporting. Now you should be able to use it inside a data center's LAN as well.

Release files will be downloadable in a few minutes.

Let me know if it addresses your requirements.
