### ISSUE TITLE
Error when running tcping

### ISSUE THREAD

**Issue by myxuchangbin** [pouriyajamshidi/tcping#59]
```
[root@localhost ~]# ./tcping 
./tcping: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./tcping)
./tcping: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./tcping)
```
Since version 1.19.0 started to report errors, I suspect it has something to do with the compilation parameter CGO_ENABLED

**Comment by pouriyajamshidi** [comment]
Thanks for bringing this to my attention.

`tcping`'s build has not changed for a very long time and indeed, it is dynamically linked.

Are you willing to share the distro/version of your Linux machine?

**Comment by myxuchangbin** [comment]
AlmaLinux 8.3
```
[root@localhost ~]# ldd --version
ldd (GNU libc) 2.28
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```
CentOS Linux release 7.9.2009 (Core)
```
[root@localhost ~]# ldd --version
ldd (GNU libc) 2.17
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

At present, only these two systems have been tested.

**Comment by pouriyajamshidi** [comment]
ah, interesting. These are quite old systems.

I will test out the statically linked version of `tcping` and if all goes well, I'll change the build process.

Not sure how it will affect the rest of the users though.

**Comment by myxuchangbin** [comment]
Consider adding a separate static link version while retaining the dynamic link version. What do you think

**Comment by pouriyajamshidi** [comment]
Good idea!

Please check this out and let me know if the issue is resolved now:

https://github.com/pouriyajamshidi/tcping/releases/download/v1.19.1/tcping_Linux_static.tar.gz

**Comment by myxuchangbin** [comment]
Great, it can work! Thank you very much!

**Comment by pouriyajamshidi** [comment]
> Great, it can work! Thank you very much!

Perfect. You are welcome.
