### ISSUE TITLE
Ouput in JSON

### ISSUE THREAD

**Issue by pouriyajamshidi** [pouriyajamshidi/tcping#6]
## Summary

Some monitoring systems could use the output of `tcping` to be in `JSON` for easier parsing and processing.  

Having a flag to change the output type would be nice. However, there are a lot to be changed since the current output is colorized.

**Comment by icemint0828** [comment]
@pouriyajamshidi 
I think **Ouput in JSON** can be divided into three processes.

* To be able to output both plane text and json text.
* To be able to choose between plane text and json text output with a flag(Something similar to this has been done in the past).
* Thinking about the contents of json text.

I'll take the first two.

**Comment by pouriyajamshidi** [comment]
@icemint0828  very clean and nice job.

the third point you mentioned, should be the exact same information as the `planePrinter`.

**Comment by icemint0828** [comment]
@pouriyajamshidi 
> the third point you mentioned, should be the exact same information as the planePrinter.

If you're not particular, this is fine.
Sorry but please work on it.

**Comment by pouriyajamshidi** [comment]
Partially addressed in https://github.com/pouriyajamshidi/tcping/commit/8296319fccd290d246c97c9a8dba52ef1b775283
