### ISSUE TITLE
Show statistics even if host is 100% unreachable

### ISSUE THREAD

**Issue by BackSpace54** [pouriyajamshidi/tcping#61]
- Is your feature request related to a problem? Please describe.

Hi,
is it possible to show statistics even if host has always been unreachable during tcping execution?
It could be useful to show to someone that the distant host is offline.

- Describe the solution you'd like

Showing statistics if 100% fails, maybe something like that:
<host> TCPing statistics
15 probes transmitted, 0 received, 100.00% packet loss
successful probes:   0
unsuccessful probes: 15
last successful probe:   N/A or never
last unsuccessful probe: Always or 100%
total uptime:   N/A or never
total downtime: <x> second
longest consecutive uptime: N/A  or never
retried to resolve hostname \<x> times
rtt min/avg/max: N/A

TCPing started at: \<start time>
TCPing ended at:   \<end time>
duration (HH:MM:SS): \<duration>

Best regards.

**Comment by pouriyajamshidi** [comment]
Hi,

Sure, this is something that can be added.

**Comment by pouriyajamshidi** [comment]
Hi @BackSpace54 ,

I just implemented the feature which you can find here:

https://github.com/pouriyajamshidi/tcping/releases/tag/v1.19.2

Let me know if this satisfies your use case.

**Comment by BackSpace54** [comment]
Hi @pouriyajamshidi
yep it's just perfect!!
Thanks.

**Comment by pouriyajamshidi** [comment]
> Hi @pouriyajamshidi yep it's just perfect!! Thanks.

My pleasure.
