### ISSUE TITLE
Using `-r n` is not retrying exactly n times

### ISSUE THREAD

**Issue by ravsii** [pouriyajamshidi/tcping#69]
_To be honest, I was rewriting the issue a couple of times because I got a little confused, what's even considered a retry here? Red `no reply ...` text or yellow `retrying to resolve ...`. It seems like the red one, I don't know if it's just me or it could also confuse others. Maybe it's working as expected, feel free to close this issue then._

_Initially I assumed that the program should just `os.Exit(0)` after `n` yellow `retrying to resolve ...` lines, which is definitely wrong._

**Describe the bug**
When using `-r` flag, it supposed to stop execution after `n` retries, but it seems like it does 1 extra.

**To Reproduce**

1. Clone repo
2. `make test`
3. `go build -o tcping tcping.go statsprinter.go` (tried using the one from `/executable`s tar, same)
4. `./tcping example.com 81 -r 3`

**Expected behavior**
Program should output `Retying to resolve` after exactly `n` tries.

**Screenshots**

https://user-images.githubusercontent.com/5007271/236703112-93e5c476-f80b-47f9-a8ad-7147804b7ad2.mp4

**Desktop (please complete the following information):**

- OS: MacOS (M1) `13.3.1`
- TCPING version: `1.21.0`
- Go version: `1.20.4`

**Comment by pouriyajamshidi** [comment]
Hi @ravsii,

I think I know where the confusion comes from! 

The `-r` flag was introduced for a feature we needed; assessing the effectiveness of our `GSLB`. The test was `tcpinging` a service in data center A, kill it, and see how the failover happens to data center B.

So in summary, `-r 3` just `retries resolving the hostname` **after 3 failed probes**, giving it a chance to continue on the new IP.

Although, I must admit, it is not the most intuitive naming. Suggestions are welcome.

Nevertheless, while testing this issue, I found out about another bug concerning this functionality which I will address soon.

Thanks!

**Comment by ravsii** [comment]
Yeah, after thinking about it for a while, I think the confusion came exactly from `retry resolving target's hostname ...` part, although after googling it it seems to be a very common concept, so probably it's just me not knowing much about networking stuff and being confused because of the terminology, sorry.

I _think_, the common term for probe is "request", so maybe mention it somewhere in flags' description. 

_Keep in mind I'm not a native speaker, so my suggestions could be invalid_

**Comment by pouriyajamshidi** [comment]
Thanks! Yea, gotta improve the docs.
