### ISSUE TITLE
Custom timeout values

### ISSUE THREAD

**Issue by pouriyajamshidi** [pouriyajamshidi/tcping#7]
## Summary

Currently `tcping` is having a hard-coded timeout value of 1 second. Being able to change this value through a flag can be useful for some scenarios but requires a major refactoring.

**Comment by mshedsilegx** [comment]
I would vote for this to be implemented as a core feature. 1s might be too aggressive on high latency links.

**Comment by pouriyajamshidi** [comment]
@mshedsilegx it is implemented now. Although not released yet. but you can compile from this repo to get the `-t` option, specifying the custom timeout value
