### ISSUE TITLE
add `-c` flag to stop after n probes

### ISSUE THREAD

**Issue by pouriyajamshidi** [pouriyajamshidi/tcping#72]
## Summary

Similar to the `ping` utility, we should also introduce the option to stop after sending `n` probes. For instance to stop after sending 4 probes:

```bash
tcping example.com 443 -c 4
```

We need to ensure that the report summary is displayed after exit.

The readme file should also be updated with the new info.

**Comment by ravsii** [comment]
Thinking about picking this up (kind of low on time for other stuff), some questions beforehand:

1. `n` means total successful + unsuccessful probes, or only one of those?
2. How should it interact with the `-r` flag?
3. Due to how recently durations were refactored, output may be incorrect sometimes. Is that ok for now or let's wait for fixes?

**Comment by pouriyajamshidi** [comment]
Hey Alex,

Thanks for being such a helping hand 🤝 

for questions 1 and 2, it means probe/ping a destination `n` times regardless of the result. similar to the `-c` flag of the `ping` utility itself. So if we say `tcping example.com 443 -c 1`, we want to exit the program after one probe, whether successful or not.

> 3. Due to how recently durations were refactored, output may be incorrect sometimes. Is that ok for now or let's wait for fixes?

That is fine. However, there won't be a release until we address #83

**Comment by ravsii** [comment]
So for `-c 3 -r 2` should ping 2 times, try to resolve, ping 1 time and quit, right?

**Comment by pouriyajamshidi** [comment]
> So for `-c 3 -r 2` should ping 2 times, try to resolve, ping 1 time and quit, right?

yes. Although in reality, it does not make much sense to specify `-r 2` when probing thrice but I get your point.

Think of this option as doing a quick check to a destination and exiting instead of using `nc -w 1` or **tcping** and then quickly `ctrl+c`.
