### ISSUE TITLE
Use standard `time.Duration` for storing/working with durations

### ISSUE THREAD

**Issue by ravsii** [pouriyajamshidi/tcping#73]
**Is your feature request related to a problem? Please describe.**
When working on #37 I found that there are some instances where duration was passed as `uint`

https://github.com/pouriyajamshidi/tcping/blob/8c3d3b777b4c07a128697901694f69c68565857c/tcping.go#L389

or `float64`

https://github.com/pouriyajamshidi/tcping/blob/8c3d3b777b4c07a128697901694f69c68565857c/tcping.go#L52

(Maybe there are others I haven't noticed)

Using bare types makes it unclear, what unit it's expecting, seconds, milliseconds or something else.

**Describe the solution you'd like**
Use canonical `time.Duration`, because all time-relation operations from the `time` package returns `time.Duration` and then a user could decide which unit does he want: hours, mins, seconds, etc.

Please tell me if there's a specific reason why it's used like that, I can be missing some context.

**Comment by pouriyajamshidi** [comment]
Hey @ravsii,

Not all the decisions we made are fresh in my memory but iircc the use of `time.Duration` would cause some tricky issues. For instance, we allow the TCP connection a second to establish and we account for that in the timing in a hardcoded way to avoid weird/inaccurate values in reports.

I really need to refresh my memory on this. Let's keep this issue open till I get some time to do a proper dive.

In the meantime you can experiment with it and possibly see if the reports  match the "real world" values.

**Comment by pouriyajamshidi** [comment]
Thanks @ravsii  🤝 

Sounds good to me.
