### ISSUE TITLE
Time conversion - Minutes to hours

### ISSUE THREAD

**Issue by pouriyajamshidi** [pouriyajamshidi/tcping#8]
## Summary

We have the ability to convert and print different time values to minutes for better readability.  
It is nicer to implement `minute` to `hour` conversion function to make it even more readable.

**Comment by icemint0828** [comment]
Hi, @pouriyajamshidi.
I'd like take up this issue.

Is it okay to add the functionality to **calcTime**?

And, may I add the like following test?

```
package main

import "testing"

func Test_calcTime(t *testing.T) {
	type args struct {
		time uint
	}
	tests := []struct {
		name string
		args args
		want string
	}{
		{
			name: "1 second",
			args: args{1},
			want: "1 second",
		},
		{
			name: "59 seconds",
			args: args{59},
			want: "59 seconds",
		},
		{
			name: "1 minute",
			args: args{1 * 60},
			want: "1 minute",
		},
		{
			name: "59 minutes",
			args: args{59 * 60},
			want: "59.0 minutes.seconds",
		},
		{
			name: "1.5 minute.seconds",
			args: args{1*60 + 5},
			want: "1.5 minute.seconds",
		},
		{
			name: "2.5 minutes.seconds",
			args: args{2*60 + 5},
			want: "2.5 minutes.seconds",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := calcTime(tt.args.time); got != tt.want {
				t.Errorf("calcTime() = %v, want %v", got, tt.want)
			}
		})
	}
}

```

**Comment by pouriyajamshidi** [comment]
Hi @icemint0828,

Thanks for reaching out. You are more than welcome to take up this ticket.

To answer your questions:

1. The check has to indeed extend `calcTime`. However, it is better to have the actual logic in a separate function like `calcSeconds` for easier referencing and refactoring in the future.
2. The test at the first glance looks good to me. But it is better to name it like `TestCalcTime` to conform to Go's styling.

If you see some other parts of the code can use test cases and improvements, please feel free to open issues for them too.

Thanks!

**Comment by icemint0828** [comment]
Thank you for your thoughtful response!
I understand both.

I get to work.

**Comment by pouriyajamshidi** [comment]
> Thank you for your thoughtful response! I understand both.
> 
> I get to work.

Thanks and best of luck!
