### ISSUE TITLE
Move any output-related logic to printers (and vice-versa)

### ISSUE THREAD

**Issue by ravsii** [pouriyajamshidi/tcping#84]
Currently, some output logic exists directly in `tcping.go`, like in example below

https://github.com/pouriyajamshidi/tcping/blob/4032ed20139c933a47851579de923d8d16b416ae/tcping.go#L290-L304

This is probably how it was initially, when there was only 1 printer. But now we have 2 printers, but also more could be added later, thus I think anything related to output should be handled by the printer of a user's choice.

Example: I'm using a JSON printer and some other tool to automatically parse it. As a user, I'd probably expect something like
```json
{ "status":"error", "hostname":"example.com.123", "port": "80" }
```
_(not the exact output, just an example)_

But not

![image](https://github.com/pouriyajamshidi/tcping/assets/5007271/285e2d1f-16bd-4190-8ad4-c1eff4ccbe28)

**Describe the solution you'd like**
Move output-related functions to printers, except for `usage()`

---

For discussion

**Comment by ravsii** [comment]
Also, it's the same the other way around, as I recently found this while investigating https://github.com/pouriyajamshidi/tcping/issues/83#issuecomment-1555288367

https://github.com/pouriyajamshidi/tcping/blob/2839563055a3e76c821d2e7db73901339ff84519/statsprinter.go#L201-L205

The printer calculates the downtime the way it wants, while, _ideally_, it should be something close to this (pseudocode):
```go
func (p *statsPlanePrinter) printTotalDownTime() {
	colorYellow("no response received for %s\n", p.downtimeDuration);
}
```

_The JSON printer is guilty of that as well._

**Comment by pouriyajamshidi** [comment]
I agree. it also helps making the code more readable.
